# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x0cuser_service\"\"\n\x0eGetUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"C\n\x0fGetUserResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x14\n\x12HealthCheckRequest\"\x92\x01\n\x13HealthCheckResponse\x12?\n\x06status\x18\x01 \x01(\x0e\x32/.user_service.HealthCheckResponse.ServingStatus\":\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x32U\n\x0bUserService\x12\x46\n\x07GetUser\x12\x1c.user_service.GetUserRequest\x1a\x1d.user_service.GetUserResponse2V\n\x06Health\x12L\n\x05\x43heck\x12 .user_service.HealthCheckRequest\x1a!.user_service.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERREQUEST']._serialized_start=36
  _globals['_GETUSERREQUEST']._serialized_end=70
  _globals['_GETUSERRESPONSE']._serialized_start=72
  _globals['_GETUSERRESPONSE']._serialized_end=139
  _globals['_HEALTHCHECKREQUEST']._serialized_start=141
  _globals['_HEALTHCHECKREQUEST']._serialized_end=161
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=164
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=310
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=252
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=310
  _globals['_USERSERVICE']._serialized_start=312
  _globals['_USERSERVICE']._serialized_end=397
  _globals['_HEALTH']._serialized_start=399
  _globals['_HEALTH']._serialized_end=485
# @@protoc_insertion_point(module_scope)
